<dna> ::= <sequence><digit>
<sequence> ::= <base>|<base><sequence>
<digit> ::= '1'|'2'|'3'|'4'
<b> ::= 'A'|'T'|'C'|'G'
<base> ::='a'|'b'|'c'|'d'|'e'|'f'|'g'|'h'|'i'|'j'|'k'|'l'|'m'|'n'|'o'|'p'|'q'|'r'|'s'|'t'|'u'|'v'|'w'|'x'|'y'|'z'|' '
<char> ::='我'|'是'|'一'|'个'|'野'|'兽'|'先'|'辈'|'爱'|'喝'|'红'|'茶'|'有'|'助'|'于'|'昏'|'睡'|'空'|'手'|'道'|'更'|'衣'|'室'|'与'|'土'|'豆'